stages:
  - build
  - test
  - sonarqube-check
  - publish
  - deploy

variables:
  PROJECT_PATH: "ICalendarNet/ICalendarNet.csproj"
  TEST_PROJECT_PATH: "ICalendarNet.UnitTest/ICalendarNet.UnitTest.csproj"
  PUBLISH_DIR: "publish"

image: mcr.microsoft.com/dotnet/sdk:10.0

before_script:
  - dotnet --version
  - dotnet tool install --global dotnet-sonarscanner

build:
  stage: build
  script:
    - dotnet build $PROJECT_PATH --configuration Release

test:
  stage: test
  script:
    - dotnet test $PROJECT_PATH --verbosity normal

sonarqube-check:
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
      - apt-get update
      - apt-get install --yes openjdk-17-jre
      - dotnet tool install --global dotnet-sonarscanner
      - export PATH=\"$PATH:$HOME/.dotnet/tools\"
      - dotnet sonarscanner begin /k:"vandenbosch_vincent_icalendarnet" /d:sonar.token="$SONAR_TOKEN" /d:sonar.host.url="$SONAR_HOST_URL" /o:"vandenbosch-vincent"
      - dotnet build $PROJECT_PATH
      - dotnet sonarscanner end /d:sonar.token=\"$SONAR_TOKEN\"
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - develop

publish:
  stage: publish
  script:
    - dotnet publish $PROJECT_PATH -f net10.0 --configuration Release --output $PUBLISH_DIR

deploy:
  stage: deploy
  only:
    - master
    - main
    - develop
  script:
    - echo "Deploying to server..."
    - TODO!!
