stages:
  - build
  - test
  - publish
  - deploy

variables:
  PROJECT_PATH: "ICalendarNet/ICalendarNet.csproj"
  TEST_PROJECT_PATH: "ICalendarNet.UnitTest/ICalendarNet.UnitTest.csproj"
  PUBLISH_DIR: "publish"

image: mcr.microsoft.com/dotnet/sdk:8.0

before_script:
  - dotnet --version

build:
  stage: build
  script:
    - dotnet build $PROJECT_PATH --configuration Release

test:
  stage: test
  script:
    - dotnet test $PROJECT_PATH --verbosity normal

publish:
  stage: publish
  script:
    - dotnet publish $PROJECT_PATH --configuration Release --output $PUBLISH_DIR

deploy:
  stage: deploy
  only:
    - develop
  script:
    - echo "Deploying to server..."
    - TODO!!
