using ICalendarNet.Converters;
using ICalendarNet.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace ICalendarNet.Extensions
{
    public static class StringExtensions
    {

        public static bool IsBase64(this string value)
        {
            Span<byte> buffer = new Span<byte>(new byte[value.Length]);
            return Convert.TryFromBase64String(value, buffer, out int bytesParsed);
        }

        public static int FindIndexOf(this ReadOnlySpan<char> span, ReadOnlySpan<char> search, int index, StringComparison stringComparison)
        {
            int found = span[index..].IndexOf(search, stringComparison);
            if (found != -1)
                found += index;
            return found;
        }

        //private static int[] TryGetIntValues(this Dictionary<string, string> values, string key, int? negativeValue = null)
        //{
        //    if (!values.TryGetValue(key, out var f))
        //        return Array.Empty<int>();
        //    var parts = f.Split(',');
        //    var result = new List<int>();
        //    foreach (var part in parts)
        //    {
        //        if (int.TryParse(part, out var intValue))
        //            if (negativeValue != null && intValue < 0)
        //                result.Add(negativeValue.Value + intValue);
        //            else
        //                result.Add(intValue);
        //    }
        //    var array = result.ToArray();
        //    Array.Sort(array);
        //    return array;
        //}

        ///// <summary>
        ///// BYDAY=1SU,-1SU (first and last Sunday of the month) or BYDAY=MO,TU,WE,TH,FR (every weekday) or BYDAY=TU (every Tuesday)
        ///// </summary>
        ///// <param name="values"></param>
        ///// <param name="key"></param>
        ///// <returns></returns>
        //private static KeyValuePair<DayOfWeek, int>[] TryGetDayOfWeek(this Dictionary<string, string> values, string key)
        //{
        //    if (!values.TryGetValue(key, out var f))
        //        return Array.Empty<KeyValuePair<DayOfWeek, int>>();
        //    var parts = f.Split(',');
        //    var result = new List<KeyValuePair<DayOfWeek, int>>();
        //    foreach (var part in parts)
        //    {
        //        var partWithoutNumber = part;
        //        var number = new string(part.TakeWhile(char.IsDigit).ToArray());
        //        int numberFound = 0;
        //        if (!string.IsNullOrEmpty(number))
        //        {
        //            var negative = part.StartsWith('-');
        //            partWithoutNumber = part[(negative ? 1 + number.Length : number.Length)..];
        //            if (int.TryParse(number, out var intValue))
        //            {
        //                numberFound = negative ? -intValue : intValue;
        //            }
        //        }
        //        if (dayMap.TryGetValue(partWithoutNumber, out var dow))
        //            result.Add(new KeyValuePair<DayOfWeek, int>(dow, numberFound));
        //    }
        //    var array = result.OrderBy(x => (int)x.Key).ToArray();
        //    return array;
        //}

        //static int GetWeekNumberOfMonth(DateTimeOffset date, DayOfWeek weekstart)
        //{
        //    date = date.Date;
        //    DateTime firstMonthDay = new DateTime(date.Year, date.Month, 1);
        //    DateTime firstMonthMonday = firstMonthDay.AddDays((weekstart + 7 - firstMonthDay.DayOfWeek) % 7);
        //    if (firstMonthMonday > date)
        //    {
        //        firstMonthDay = firstMonthDay.AddMonths(-1);
        //        firstMonthMonday = firstMonthDay.AddDays((weekstart + 7 - firstMonthDay.DayOfWeek) % 7);
        //    }
        //    return (date - firstMonthMonday).Days / 7 + 1;
        //}

        ///// <summary>
        ///// Generates a list of date strings from an RRULE (e.g., 'FREQ=WEEKLY;BYDAY=MO,WE,FR'), starting from startDate.
        ///// Supports FREQ, INTERVAL, BYDAY, COUNT, UNTIL. Calendar-agnostic, string-in, string-out.
        ///// </summary>
        ///// <param name="rrule">The RRULE string (e.g., 'FREQ=WEEKLY;BYDAY=MO,WE,FR').</param>
        ///// <param name="startDate">The start date string (e.g., '2024-05-01').</param>
        ///// <param name="endDate">An optional end date string (e.g., '2024-05-05') to limit the sequence.</param>
        ///// <param name="count">An optional maximum number of occurrences to generate.</param>
        ///// <returns>A list of date strings generated by the RRULE.</returns>
        //public static List<DateTimeOffset> ParseRRule(string rrule, DateTimeOffset startDate, DateTimeOffset? endDate = null, int? count = null)
        //{
        //    if (string.IsNullOrWhiteSpace(rrule) || !rrule.Contains("FREQ"))
        //        throw new ArgumentException("RRULE is required.");
        //    DateTimeOffset? dtEnd = endDate;
        //    DateTimeOffset dt = startDate;
        //    var rules = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        //    foreach (var part in rrule.Split(';'))
        //    {
        //        var kv = part.Split('=');
        //        if (kv.Length == 2)
        //            rules[kv[0].Trim()] = kv[1].Trim();
        //    }
        //    Calendar cal = new CultureInfo("en-US").Calendar;
        //    var freq = rules.TryGetValue("FREQ", out var f) ? f.ToUpperInvariant() : "DAILY";
        //    var interval = rules.TryGetValue("INTERVAL", out var i) && int.TryParse(i, out var iv) ? iv : 1;
        //    var until = rules.TryGetValue("UNTIL", out var u) ? u : null;
        //    var maxCount = rules.TryGetValue("COUNT", out var c) && int.TryParse(c, out var cnt) ? cnt : (count ?? int.MaxValue);
        //    if (count.HasValue && maxCount > count.Value)
        //        maxCount = count.Value;
        //    var weekStart = rules.TryGetValue("WKST", out var ws) ? ws : null;
        //    var dayStart = weekStart != null && dayMap.TryGetValue(weekStart, out var wsDow) ? wsDow : DayOfWeek.Sunday;
        //    var bymonth = rules.TryGetIntValues("BYMONTH");
        //    var byweekno = rules.TryGetIntValues("BYWEEKNO", 52); //[plus / minus] ordwk
        //    var byyearday = rules.TryGetIntValues("BYYEARDAY", cal.GetDaysInYear(dt.Year)); //[plus / minus] ordyrday
        //    var bymonthday = rules.TryGetIntValues("BYMONTHDAY", cal.GetDaysInMonth(dt.Year, dt.Month)); //[[plus / minus] ordwk] weekday
        //    var byday = rules.TryGetDayOfWeek("BYDAY"); //[[plus / minus] ordwk] weekday
        //    var byhour = rules.TryGetIntValues("BYHOUR");
        //    var byminute = rules.TryGetIntValues("BYMINUTE");
        //    var bysecond = rules.TryGetIntValues("BYSECOND");
        //    var result = new List<DateTimeOffset>();
        //    if (until != null && ICalTypeConverters.ConvertToDateTimeOffset(until) is DateTimeOffset untilDt)
        //    {
        //        if (endDate == null || untilDt < endDate)
        //            endDate = untilDt;
        //    }
        //    int added = 0;
        //    var current = dt;
        //    while (added < maxCount && (dtEnd == null || current <= dtEnd))
        //    {
        //        bool add = true;
        //        Frequent nextFreq = Enum.Parse<Frequent>(freq);
        //        int nextInterval = interval;
        //        DateTimeOffset? nextDate = null;
        //        if (add && bymonth.Length > 0)
        //        {
        //            add = Array.Exists(bymonth, d => d == current.Month);
        //            nextFreq = nextFreq < Frequent.MONTHLY ? nextFreq : Frequent.MONTHLY;
        //            nextInterval = 1;
        //        }
        //        if (add && byweekno.Length > 0)
        //        {
        //            var weekday = cal.GetWeekOfYear(current.DateTime, CalendarWeekRule.FirstDay, dayStart);
        //            add = Array.Exists(byweekno, d => d == weekday);
        //            nextFreq = nextFreq < Frequent.DAILY ? nextFreq : Frequent.DAILY;
        //            nextInterval = 1;
        //        }
        //        if (add && byyearday.Length > 0)
        //        {
        //            add = Array.Exists(byyearday, d => d == current.DayOfYear);
        //            nextFreq = nextFreq < Frequent.DAILY ? nextFreq : Frequent.DAILY;
        //            nextInterval = 1;
        //        }
        //        if (add && bymonthday.Length > 0)
        //        {
        //            add = Array.Exists(bymonthday, d => d == current.Day);
        //            nextFreq = nextFreq < Frequent.DAILY ? nextFreq : Frequent.DAILY;
        //            nextInterval = 1;
        //        }
        //        if (add && byday.Length > 0)
        //        {
        //            int idx = Array.IndexOf(byday.Select(t => t.Key).ToArray(), current.DayOfWeek);
        //            if (idx == -1)
        //                add = false;
        //            else if (byday[idx].Value > 0)
        //            {
        //                var dayOfWeekRule = byday[idx];
        //                if (freq == "MONTHLY" && GetWeekNumberOfMonth(current, dayStart) != dayOfWeekRule.Value)
        //                    add = false;
        //                if (freq == "YEARLY" && cal.GetWeekOfYear(current.DateTime, CalendarWeekRule.FirstDay, dayStart) != dayOfWeekRule.Value)
        //                    add = false;
        //            }
        //            else if (byday[idx].Value < 0)
        //            {
        //                var dayOfWeekRule = byday[idx];
        //                var daysInMonth = DateTime.DaysInMonth(current.Year, current.Month);
        //                var lastDayOfWeekInMonth = new DateTime(current.Year, current.Month, daysInMonth);
        //                while (lastDayOfWeekInMonth.DayOfWeek != current.DayOfWeek)
        //                    lastDayOfWeekInMonth = lastDayOfWeekInMonth.AddDays(-1);
        //                if (current.Day != lastDayOfWeekInMonth.Day - (dayOfWeekRule.Value + 1) * 7)
        //                    add = false;
        //            }
        //            nextFreq = nextFreq < Frequent.DAILY ? nextFreq : Frequent.DAILY;
        //            nextInterval = 1;
        //        }
        //        if (add && byhour.Length > 0)
        //        {
        //            add = Array.Exists(byhour, d => d == current.Hour);
        //            nextFreq = nextFreq < Frequent.HOURLY ? nextFreq : Frequent.HOURLY;
        //            nextInterval = 1;
        //        }
        //        if (add && byminute.Length > 0)
        //        {
        //            add = Array.Exists(byminute, d => d == current.Minute);
        //            nextFreq = nextFreq < Frequent.MINUTELY ? nextFreq : Frequent.MINUTELY;
        //            nextInterval = 1;
        //        }
        //        if (add && bysecond.Length > 0)
        //        {
        //            add = Array.Exists(bysecond, d => d == current.Second);
        //            nextFreq = nextFreq < Frequent.SECONDLY ? nextFreq : Frequent.SECONDLY;
        //            nextInterval = 1;
        //        }
        //        if (add)
        //        {
        //            result.Add(current);
        //            added++;
        //        }
        //        current = nextDate ?? nextFreq switch
        //        {
        //            Frequent.SECONDLY => current.AddSeconds(nextInterval),
        //            Frequent.MINUTELY => current.AddMinutes(nextInterval),
        //            Frequent.HOURLY => current.AddHours(nextInterval),
        //            Frequent.DAILY => current.AddDays(nextInterval),
        //            Frequent.WEEKLY => byweekno.Length > 0 ? current.AddDays(nextInterval) : current.AddDays(7 * nextInterval),
        //            Frequent.MONTHLY => bymonthday.Length > 0 ? current.AddDays(nextInterval) : current.AddMonths(nextInterval),
        //            Frequent.YEARLY => current.AddYears(nextInterval),
        //            _ => throw new NotSupportedException($"FREQ={freq} not supported"),
        //        };
        //    }
        //    return result;
        //}
    }
}