using ICalendarNet.Extensions;
using ICalendarNet.Models.DataTypes;
using ICalendarNet.Models.DataTypes.Recurrence;
using ICalendarNet.Models.Enum;
using System;
using System.Linq;

namespace ICalendarNet.Logic.Recurrence
{
    public static partial class RecurrenceRuleEvaluator
    {
        /// <summary>
        /// Applies RFC 5545 defaults to the BY-parts of <paramref name="r"/> based on
        /// the <paramref name="referenceDate"/> (DTSTART). The returned rule is a
        /// mutated copy ready for evaluation.
        /// </summary>
        private static CalendarRecurrenceRule ProcessRecurrencePattern(
            DateTimeOffset referenceDate,
            CalendarRecurrenceRule r)
        {
            ApplyTimeOfDayDefaults(referenceDate, r);
            ApplyDateDefaults(referenceDate, r);
            PreOrderNonNegativeByParts(r);

            return r;
        }

        private static void ApplyTimeOfDayDefaults(DateTimeOffset referenceDate, CalendarRecurrenceRule r)
        {
            if (referenceDate.HasTime())
            {
                // NOTE: Fixes a bug where all-day events have BySecond/ByMinute/ByHour added incorrectly
                if (r.Frequency > FrequencyType.Secondly && r.BySecond.Count == 0)
                    r.BySecond.Add(referenceDate.Second);

                if (r.Frequency > FrequencyType.Minutely && r.ByMinute.Count == 0)
                    r.ByMinute.Add(referenceDate.Minute);

                if (r.Frequency > FrequencyType.Hourly && r.ByHour.Count == 0)
                    r.ByHour.Add(referenceDate.Hour);
            }
            else
            {
                // The BYSECOND, BYMINUTE and BYHOUR rule parts MUST NOT be specified
                // when the associated "DTSTART" property has a DATE value type.
                // These rule parts MUST be ignored in RECUR value that violate the
                // above requirement (e.g., generated by applications that pre-date
                // this revision of iCalendar).
                r.BySecond.Clear(); r.BySecond.Add(0);
                r.ByMinute.Clear(); r.ByMinute.Add(0);
                r.ByHour.Clear(); r.ByHour.Add(0);
            }
        }

        private static void ApplyDateDefaults(DateTimeOffset referenceDate, CalendarRecurrenceRule r)
        {
            // If BYDAY, BYYEARDAY, or BYWEEKNO is specified, then
            // we don't default BYDAY, BYMONTH or BYMONTHDAY
            if (r.ByDay.Count != 0)
                return;

            // If the frequency is weekly, use the original date's day of week.
            // NOTE: fixes WeeklyCount1() and WeeklyUntil1() handling
            // If BYWEEKNO is specified and BYMONTHDAY/BYYEARDAY is not specified,
            // then let's add BYDAY to BYWEEKNO.
            // NOTE: fixes YearlyByWeekNoX() handling
            if (r.Frequency == FrequencyType.Weekly
                || (r.ByWeekNo.Count > 0 && r.ByMonthDay.Count == 0 && r.ByYearDay.Count == 0))
            {
                r.ByDay.Add(new WeekDay(referenceDate.DayOfWeek));
            }

            // If BYMONTHDAY is not specified, default to the current day of month.
            // NOTE: fixes YearlyByMonth1() handling, added BYYEARDAY exclusion
            // to fix YearlyCountByYearDay1() handling
            if (r.Frequency > FrequencyType.Weekly
                && r.ByWeekNo.Count == 0
                && r.ByYearDay.Count == 0
                && r.ByMonthDay.Count == 0)
            {
                r.ByMonthDay.Add(referenceDate.Day);
            }

            // If BYMONTH is not specified, default to the current month.
            // NOTE: fixes YearlyCountByYearDay1() handling
            if (r.Frequency > FrequencyType.Monthly
                && r.ByWeekNo.Count == 0
                && r.ByYearDay.Count == 0
                && r.ByMonth.Count == 0)
            {
                r.ByMonth.Add(referenceDate.Month);
            }
        }

        /// <summary>
        /// Pre-order those BY values that don't allow for negative values. Those with
        /// negative values can only be ordered once the individual position is known.
        /// </summary>
        private static void PreOrderNonNegativeByParts(CalendarRecurrenceRule r)
        {
            if (r.BySecond.Count > 0) r.BySecond = [.. r.BySecond.OrderBy(x => x)];
            if (r.ByMinute.Count > 0) r.ByMinute = [.. r.ByMinute.OrderBy(x => x)];
            if (r.ByHour.Count > 0) r.ByHour = [.. r.ByHour.OrderBy(x => x)];
            if (r.ByMonth.Count > 0) r.ByMonth = [.. r.ByMonth.OrderBy(x => x)];
        }
    }
}