<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0;</TargetFrameworks>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>VandenboschVincent</Authors>
    <Description>For Serializing/Deserializing/Changing ICal Files</Description>
    <PackageProjectUrl>https://github.com/VandenboschVincent/ICalendarNet</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/VandenboschVincent/ICalendarNet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
	<LangVersion>13.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
